---
title: "R Notebook"
output md_document
---

#### Load the lib and data
```{r}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(arrow)
```
```{r}
data_path <- "/Users/kaz/Desktop/MMA - WINTER Code/Talent_data/app_data_starter.feather" # change this to your path
applications <- arrow::read_feather(data_path)
```

### Add individual level variables like gender and race
```{r}
library(gender)
examiner_names <- applications %>%
        distinct(examiner_name_first)

examiner_names_gender <- examiner_names %>%
        do(results = gender(.$examiner_name_first, method = "ssa")) %>%
        unnest(cols = c(results), keep_empty = TRUE) %>%
        select(
                examiner_name_first = name,
                gender,
                proportion_female)

# remove extra colums from the gender table
examiner_names_gender <- examiner_names_gender %>%
        select(examiner_name_first, gender)

# joining gender back to the dataset
applications <- applications %>%
        left_join(examiner_names_gender, by = "examiner_name_first")

# cleaning up
rm(examiner_names)
rm(examiner_names_gender)
gc()



library(wru)

examiner_surnames <- applications %>%
        select(surname = examiner_name_last) %>%
        distinct()

examiner_race <- predict_race(voter.file = examiner_surnames, surname.only = T) %>%
        as_tibble()

examiner_race <- examiner_race %>%
        mutate(max_race_p = pmax(pred.asi, pred.bla, pred.his, pred.oth, pred.whi)) %>%
        mutate(race = case_when(
                max_race_p == pred.asi ~ "Asian",
                max_race_p == pred.bla ~ "black",
                max_race_p == pred.his ~ "Hispanic",
                max_race_p == pred.oth ~ "other",
                max_race_p == pred.whi ~ "white",
                TRUE ~ NA_character_
        ))


# removing extra columns
examiner_race <- examiner_race %>%
        select(surname,race)

applications <- applications %>%
        left_join(examiner_race, by = c("examiner_name_last" = "surname"))

rm(examiner_race)
rm(examiner_surnames)
gc()

library(lubridate) # to work with dates

examiner_dates <- applications %>%
        select(examiner_id, filing_date, appl_status_date)

examiner_dates <- examiner_dates %>%
        mutate(start_date = ymd(filing_date), end_date = as_date(dmy_hms(appl_status_date)))

examiner_dates <- examiner_dates %>%
        group_by(examiner_id) %>%
        summarise(
                earliest_date = min(start_date, na.rm = TRUE),
                latest_date = max(end_date, na.rm = TRUE),
                tenure_days = interval(earliest_date, latest_date) %/% days(1)
        ) %>%
        filter(year(latest_date)<2018)

applications <- applications %>%
        left_join(examiner_dates, by = "examiner_id")

rm(examiner_dates)
gc()
```


#### Ex2 Vairables
```{r}
# Convert filing_date to Date format and create a quarter variable
applications$filing_date <- as.Date(applications$filing_date)
applications$quarter <- paste0(year(applications$filing_date), "/", quarter(applications$filing_date))

# Aggregate applications by quarter and examiner
applications <- applications %>%
        group_by(quarter, examiner_id) %>%
        mutate(new_applications = n_distinct(application_number)) %>%
        ungroup()

applications <- applications %>%
        group_by(quarter, examiner_id) %>%
        mutate(ISSUED_applications = sum(disposal_type == "ISS" & !duplicated(application_number)))

applications <- applications %>%
        group_by(quarter, examiner_id) %>%
        mutate(abn_applications = sum(disposal_type == "ABN" & !duplicated(application_number)))

applications <- applications %>%
        group_by(quarter, examiner_id) %>%
        mutate(PEN_applications = sum(disposal_type == "PEND" & !duplicated(application_number)))

applications <- applications %>%
        group_by(quarter,examiner_art_unit) %>%
        mutate(examiner_art_unit_num =  n_distinct(examiner_id))%>%
        ungroup()

applications <- applications %>%
        group_by(quarter, examiner_art_unit) %>%
        mutate(women_in_art_unit  = sum(gender.y == "female" & !duplicated(examiner_id)))

applications <- applications %>%
        group_by(quarter, examiner_art_unit) %>%
        mutate(Asian_in_art_unit  = sum(race.y == "Asian" & !duplicated(examiner_id)))

applications <- applications %>%
        group_by(quarter, examiner_art_unit) %>%
        mutate(Black_in_art_unit  = sum(race.y == "black" & !duplicated(examiner_id)))


applications <- applications %>%
        group_by(quarter, examiner_art_unit) %>%
        mutate(Hispanic_in_art_unit  = sum(race.y == "Hispanic" & !duplicated(examiner_id)))

applications <- applications %>%
        group_by(quarter, examiner_art_unit) %>%
        mutate(Other_in_art_unit  = sum(race.y == "other" & !duplicated(examiner_id)))

applications <- applications %>%
        group_by(quarter, examiner_art_unit) %>%
        mutate(White_in_art_unit  = sum(race.y == "white" & !duplicated(examiner_id)))
```

```{r}
# sort by examiner_id and quarter
applications <- applications %>%
        arrange(examiner_id, quarter)

applications_selected <- applications %>%
        select(
                application_number,
                examiner_id,
                examiner_name_first,
                examiner_name_middle,
                examiner_name_last,
                tc,
                quarter,
                new_applications,
                ISSUED_applications,
                abn_applications,
                PEN_applications,
                examiner_art_unit,
                women_in_art_unit,
                Asian_in_art_unit,
                Black_in_art_unit,
                Other_in_art_unit,
                White_in_art_unit,
                ends_with(".x")  # Select columns that end with '_x'
        ) %>%
        rename_with(~ str_remove(., ".x"), ends_with(".x"))  # Remove the '_x' suffix
```


```{r}
# find the latest time quarter for each examiner
overall_max_quarter <- "2017/1"

# filter dataset to exclude the latest quarter
applications_selected <- applications_selected %>%
        filter(quarter <= overall_max_quarter)
```


```{r}
# add the separation indicator variable
applications_selected <- applications_selected %>%
        group_by(examiner_id) %>%
        mutate(max_quarter_examiner = max(quarter)) %>%
        ungroup() %>%
        mutate(separation_indicator = if_else(max_quarter_examiner < overall_max_quarter, 1, 0))
```

```{r}
# AU move indicator
applications_selected <- applications_selected %>%
  group_by(examiner_id) %>%
  mutate(au_move_indicator = if_else(examiner_art_unit != lag(examiner_art_unit), 1, 0)) %>%
  ungroup()

# Fill NA for the au_move_indicator
applications_selected <- applications_selected %>%
  mutate(au_move_indicator = if_else(is.na(au_move_indicator), 0, au_move_indicator))
```


```{r}
# some other cleaning
# drop columns: assumed we don't need them anymore
applications_selected <- applications_selected %>%
  select(-c(max_quarter_examiner, earliest_date, latest_date, tc))


```

```{r}
df <- applications_selected
```

#### Aggreagate to panel level (quarterly)
```{r}
# individual level data
indi_attributes <- df %>%
  select(gender, race, examiner_id) %>%
  distinct(examiner_id, .keep_all = TRUE)

panel_df <- df %>%
  group_by(examiner_id, quarter) %>%
  summarize(
    new_applications = mean(new_applications, na.rm = TRUE),
    ISSUED_applications = mean(ISSUED_applications, na.rm = TRUE),
    total_abn_applications = mean(abn_applications, na.rm = TRUE),
    total_PEN_applications = mean(PEN_applications, na.rm = TRUE),
    tenure_days = mean(tenure_days, na.rm = TRUE),
    women_in_art_unit = mean(women_in_art_unit, na.rm = TRUE),
    Asian_in_art_unit = mean(Asian_in_art_unit, na.rm = TRUE),
    Black_in_art_unit = mean(Black_in_art_unit, na.rm = TRUE),
    Other_in_art_unit = mean(Other_in_art_unit, na.rm = TRUE),
    White_in_art_unit = mean(White_in_art_unit, na.rm = TRUE),
    separation_indicator = mean(separation_indicator, na.rm = TRUE),
    au_move_indicator = sum(au_move_indicator, na.rm = TRUE)
  )


panel_df <- panel_df %>%
  left_join(indi_attributes, by = "examiner_id")


panel_df <- panel_df %>%
  mutate(
    examiner_id = as.integer(examiner_id),
    quarter = as.character(quarter),  # or you could separate into year and quarter
    tenure_days = as.numeric(tenure_days),  # Assuming you keep the .x column
    separation_indicator = as.integer(separation_indicator),
    au_move_indicator = as.integer(au_move_indicator),
    gender = as.factor(gender),
    race = as.factor(race)
  )

```

```{r}
max(panel_df$quarter)
```



```{r}
# for those with separation indicator = 1, make their last quarter = 1 and the rest 0.

panel_df <- panel_df %>%
  group_by(examiner_id) %>%
  mutate(
    last_observation = ifelse(row_number() == n(), 1, 0), # Identify the last observation
    separation_indicator = ifelse(last_observation == 1 & any(separation_indicator == 1), 1, 0)
  ) %>%
  select(-last_observation) %>% # Remove the helper column
  ungroup()

```


```{r}
# change the au_move_indicator - if > 1 then 1
panel_df$au_move_indicator[panel_df$au_move_indicator > 1] <- 1
```


```{r}
# export the data
write_feather(panel_df, "/Users/kaz/Desktop/MMA - WINTER Code/Talent_data/panel_df.feather")
```
